### ISSUE TITLE
Activity Unit Test

### ISSUE THREAD

**Issue by pedrohenriquerls** [juanchosaravia/Keddit#3]
First of all, thanks a lot for the article and for this repository with the example, you do a great job here 😄
But I thought some things to you add on the example, if possible.
Make a unit test for the activity using the rxjava to answer some questions.
Questions like:
How you can config the test to deal with the schedulers into the activity?
How to assert the result of one observable?

**Comment by juanchosaravia** [comment]
Hi @pedrohenriquerls, I don't recommend you to create unit test for the Activity as you will have a lot of problems mocking Android specific objects. Maybe you could create Instrumentation test for this. Another option is to use MVP or MVVM patterns that will allow you to unit test those parts of the app, but I didn't address them in this tutorial and that's why I didn't create tests for this. I think it would be great to evolve this app with one of these patterns :)
